name: fi_intern_training
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab>=2.2.10
  - numpy>=1.21
  - pandas=1.3.4
  - matplotlib=3.4.3
  - xarray=0.20.1
  - netcdf4=1.5.7
  - dask=2.19.0
  - zarr=2.11.3
  - seaborn=0.11.2
  - cartopy=0.18.0
  - python=3.9.7
  - scikit-learn=1.0
  - statsmodels=0.13.0
  - s3fs=0.2.0
  - fsspec=2021.8.1
  - hvplot=0.7.3
  - wget=1.20.3
  - aiohttp=3.7.4.post0
  - geoviews=1.9.2
  - geopy=2.2.0
